name: Release Monorepo Packages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release changed packages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - chimp-core
          - git-chimp
          - doc-chimp
          - release-chimp

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies at root
        run: npm ci

      - name: Build all packages
        run: npx turbo run build

      - name: Bump, changelog, commit, and tag
        working-directory: packages/${{ matrix.package }}
        run: |
          git config user.name "chimp-bot"
          git config user.email "chimp-bot@chimp-stack.com"
          node ../release-chimp/dist/cli.js bump --ci

      - name: Publish to npm
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
